### PR TITLE
Extensibility, small bugfixes, refactorings, compatibility to PHP 8.2

### PR DESCRIPTION
**Pull request by NlL5**
I wanted to use this library in our project, because it looked quite promising!
Though, our project uses different URL paths and logging mechanics and PHP 8.2. I noticed some small bugs, fixed them and could not resist to refactor some small things.

I think I tested my changes enough to say that I didn't introduce new bugs.

If I haven't commented my changes enough, feel free to ask and I will extend my commit messages or add comments.

### CODE REVIEW

**Comment by augmentedlogic** [comment]
Thank you, will look over that in the next days and submit a new package

**Comment by NlL5** [comment]
Nice, thanks alot!

**Comment by augmentedlogic** [comment]
Has been merged.

Note that I change the is_valid_image method to be a bit more relaxed. getimagesize() returns a Boolean if the file is no image at all (which caused a fatal error). we also need to check only if it is an image at all, so $a is an array we return true.

composer package is already available as v0.5.1 on packagist

**Comment by NlL5** [comment]
Oh, this is really nice!
Today, I even had this problem, because OSM returned "Access denied. See https://operations.osmfoundation.org/policies/tiles/".
So your change is really welcome.

**Pull request merged**
